name: CI-build-test

on:
  workflow_run:
    workflows: ["CI-riken"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download artifact from ci-riken
      uses: actions/download-artifact@v2
      with:
        name: hex_hello_world
        path: hex_hello_world  # Path to save the downloaded artifact

    - name: Use the downloaded artifact
      run: |
        # Commands to use the artifact
        echo "Running with the downloaded artifact..."
        ./hex_hello_world
