name: CI-build-test

on:
  workflow_run:
    workflows: ["CI-riken"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4.1.8
        with:
          name: hex_hello_world

      - name: Set permissions
        run: chmod +x hex_hello_world

      - name: Run binary
        run: ./hex_hello_world
