name: CI-riken

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a single command using the runners shell to compile the C program
      - name: gcc compile
        run: |
          gcc HelloWorld.c -o hex_hello_world
          pwd
          ls -la

      # Upload the compiled artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: hex_hello_world
          path: hex_hello_world  # Path to the compiled artifact

  # Trigger the next workflow upon successful completion of this one
  trigger-next-workflow:
    needs: build
    runs-on: ubuntu-latest
    if: success()
    steps:
    - name: Trigger next workflow
      uses: benc-uk/workflow-dispatch@v1
      with:
        workflow: ci-build-test.yml
        token: ${{ secrets.GITHUB_TOKEN }}
