name: CI-riken

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build project
      run: |
        # Build commands
        echo "Building project..."
        gcc HelloWorld.c -o hex_hello_world
        pwd
        ls -la

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: hex_hello_world
        path: hex_hello_world  # Path to the compiled artifact
